apiVersion: v1
kind: Service
metadata:
  name: {{ include "virus-tracker.fullname" . }}-backend
  labels:
    {{- include "virus-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "virus-tracker.labels" . | nindent 4 }}
