{{- if .Values.backend.env.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virus-tracker.fullname" . }}-backend
  labels:
    {{- include "virus-tracker.labels" . | nindent 4 }}
stringData:
  JWT_SECRET: {{ .Values.backend.env.jwtSecret | quote }}
  {{- if .Values.backend.env.apiKey }}
  API_KEY: {{ .Values.backend.env.apiKey | quote }}
  {{- end }}
{{- end }}
