apiVersion: v1
kind: Service
metadata:
  name: {{ include "virus-tracker.fullname" . }}-frontend
  labels:
    {{- include "virus-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/component: frontend
    {{- include "virus-tracker.labels" . | nindent 4 }}
